#!/bin/bash
dotenv

OUT=$(curl -X "PUT" "https://api.spotify.com/v1/me/player/pause" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN")

if [ "${#OUT}" -gt 1 ]; then
	exit 1
fi

