#!/bin/bash
dotenv
SRC="$PWD"
SHUFFLE="true"

while getopts ":-:" OPTION; do
	case $OPTION in
		-)
			case $OPTARG in
				on)
					SHUFFLE="true"
				;;
				off)
					SHUFFLE="false"
				;;
			esac
		;;
		*)
			echo "Correct Usage: shuffle [--off] [--on]"
		;;
	esac
done

curl -X "PUT" "https://api.spotify.com/v1/me/player/shuffle?state=$SHUFFLE" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN"
